### ISSUE TITLE
Route being cut after edit - Destination changes after edits

### ISSUE THREAD

**Issue by Baldo81** [osmandapp/OsmAnd-iOS#2816]
**Description of the problem:**

_I'm attaching the gpx as an example and video of the issue._

As a user I edit a route created in Osmand.
I can delete/move/add a waypoint on it.
When I'm done I tap DONE and the route is saved.

At this moment the route is missing of the last part of it, it **ends on point 83** instead of point 92 that is the destination.  

BUT if I edit again the route, I see that the route still has 92 point but the destination (and navigation between points) ends on point 83.

Notes: 
1. The navigation from point 82 to 83 is a straight line, from point 83 to 84 is using the bike profile.
2. the cut after the edit happens always from point 83

**Enviroment:**
Tested on Osmand 4.4.6
Devices tested: IPad Pro 11 (2nd generation) os 16.3.1 and Iphone 13 os 16.4.1

**Attachments:**
Video showing the issue on IPAD: https://youtu.be/QS5g2VGptu8
Zipped GPX file used

[Pavese e sabbia nel PO - RITORNO.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/11294208/Pavese.e.sabbia.nel.PO.-.RITORNO.gpx.zip)

**Comment by Max1234-Ita** [comment]
@Baldo81, what is the original navigation from point 1 to 82 and from point 84 to the end? 
I opened the _gpx_ in my Android device and it was "Truck". is that correct?. If so, it looks like  OsmAnd has used different profiles in the edits.

**Comment by Baldo81** [comment]
> @Baldo81, what is the original navigation from point 1 to 82 and from point 84 to the end? I opened the _gpx_ in my Android device and it was "Truck". is that correct?. If so, it looks like OsmAnd has used different profiles in the edits.

It depends, I used different profiles depending on the path I needed to use between points. 
The route will be followed by motorcycle, but on some paths osmand wasn't allowing me to pass so I had to change from different profiles (Bike, foot, straight line)


MAybe the Truck you're seeing is my Dirt Bike profile?! 
please find attached my profiles
[Profiles.zip](https://github.com/osmandapp/OsmAnd-iOS/files/11294499/Profiles.zip)

**Comment by Zirochkabila** [comment]
4.4.8.3
Result can be reproduced only with the user's track

### Step to reproduce

- Select track
- Actions
- Edit track
- Chose any point 
- Delete 
- Done

**Comment by Baldo81** [comment]
> 4.4.8.3 Result can be reproduced only with the user's track
> 
> ### Step to reproduce
> * Select track
> * Actions
> * Edit track
> * Chose any point
> * Delete
> * Done

Hi, user’s track has been provided attached to 1st post

**Comment by Baldo81** [comment]
Issue still present. It’s impossibile to edit any track on iPad or iPhone as the track is being cut

**Comment by Baldo81** [comment]
Video of the issue: https://youtu.be/xQSheQIHI7g

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/374077afb6a3eaa143113fc807acece8880254f7
