### ISSUE TITLE
Wrong interface colors when I select a track

### ISSUE THREAD

**Issue by tatobox** [osmandapp/OsmAnd-iOS#3418]
<details>
<summary>Screenshot</summary>
 <table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/153958793/603340bc-f20c-4e76-a1d5-7fabef509b79" width="300" height="auto"/> </td>
  </tr>
 </table>
</details>

When I select an existing track some graphical artifacts appear: status bar at the top, button bar at the bottom and the panel headers are in the wrong color. It happens when the map is in night mode and the profile is in dark mode.

\> iPhone SE 1st gen
\> iOS 15.8
\> TestFlight 4.7.1.6

**Comment by dmpr0** [comment]
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/235f7a9e-9a9a-49e1-9247-cf97e2af69c0"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/09758b05-1090-4bef-8b2a-366c1b58708f"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

I can't reproduce the issue. Tested on iPhone SE Simulator with iOS 15.5


@tatobox could you please provide profile settings? You can go to Menu - Settings - Profile - Export.

**Comment by tatobox** [comment]
After going through the profiles and returning to the starting profile the situation has improved, the panel header is correct, but the rest still has inconsistencies (screenshot attached).
@dmpr0  In your day mode screenshot the information in the top bar (carrier, time, battery level) are white but it should be black.
Attached here you will find my exported profile
<details>
<summary>Screenshot</summary>
![IMG_8528](https://github.com/osmandapp/OsmAnd-iOS/assets/153958793/281e677f-2fdc-4859-a081-b7d8d83704a2)
![IMG_8529](https://github.com/osmandapp/OsmAnd-iOS/assets/153958793/b4faff16-8370-49ce-ae1a-3e3236f900ff)

</details>

[Guida.osf.zip](https://github.com/osmandapp/OsmAnd-iOS/files/14191888/Guida.osf.zip)

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Turn on the dark mode and select any track.

OsmAnd TestFlight 4.7.1.6

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/bce90c74-6ec3-4052-b575-04b935d1dd42"  width="300" height="auto"/> </th>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/2b6a2787-3c31-433d-bbfe-48d266758ded"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3499

**Comment by DmitrySvetlichny** [comment]
Fixed status bar styling on multiple screens. The remaining bugs from the issue are not reproduced.

**Comment by yuriiurshuliak** [comment]
The bug was not fixed. When switching to dark mode, the colors of the panel are mixed, one part is dark, the other part is light.

OsmAnd TestFlight 4.7.2.10
iOS 16.4.1

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/2eb5a219-42c6-4283-b2e7-764f13d9126b

**Comment by DmitrySvetlichny** [comment]
Fix dark app theme:
- Fix toolBar AppTheme OATrackMenuViewControllerState;
- Fix AppTheme OABaseButtonsViewController;
- Fix AppTheme OAIconTitleIconRoundCell;
- Fix AppTheme NavigationBar OAChoosePlanViewController;
- Fix AppTheme closeButton OARoutePlanningHudViewController;
- Fix AppTheme closeButton OADashboardViewController OAMapSettingsTerrainParametersViewController OAWeatherLayerSettingsViewController;
- Fix AppTheme toolBar TravelArticleDialogViewController;
- Fix AppTheme topButton OABaseBigTitleSettingsViewController OARouteLineAppearanceHudViewController OATrackMenuAppearanceHudViewController;

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3525

**Comment by yuriiurshuliak** [comment]
Upon rechecking, the issue persists. When switching to dark mode, the colors do not align with the theme.

OsmAnd TestFlight 4.7.2.11
iOS 16.4.1

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/624d68ad-86b1-45ae-95a8-6bb7d83f7176

**Comment by DmitryAlexei** [comment]
TestFlight 4.7.3.2
Issue cannot be reproduced anymore

**Comment by tatobox** [comment]
@vshcherb as you can see from the video the problem is not completely solved.
The bottom bar in the Markers panel is the wrong color
The bottom bar in the Widgets panel is the wrong color
The Quick Action panel is the wrong color
Thank you

iPad Pro 12.9 1st (ML0N2TY/A)
iPadOS 16.7.7
TestFlight 4.7.3.7

<details>
<summary>Screenshoot</summary>
<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/153958793/742a5c05-572c-46a9-bd04-fcaabb553dff"  width="600" height="auto"/> </td>
  </tr>
</table>
</details>

**Comment by vshcherb** [comment]
Sorry didn't understand it may be. Widgets follow the color of the day / night mode as designed to switch for driving or to fit the map. UI follows the system setting. 
We don't have the setting yet that map follows system mode however there is an issue for that open

**Comment by tatobox** [comment]
Sorry, the images probably help you understand better what I wanted to say.
The bottom bar in the Markers and Widgets panels is still the wrong color

<details>
<summary>Screenshoot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/153958793/8dd16414-375c-4d8e-a361-0c3c3742f865"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/153958793/27b0ac09-6c35-4432-b766-879290e4a7ed"  width="300" height="auto"/> </td>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/153958793/920ddd28-1191-4e14-81a7-07a24715fd8d"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/153958793/6a4695fd-c189-499f-9f39-c7015b68e4e9"  width="300" height="auto"/> </td>
  </tr>
</table>
</details>

**Comment by yuriiurshuliak** [comment]
On the new version of TestFlight, I still have this issue. Most likely, this is due to an older version of iOS.

OsmAnd TestFlight 4.7.3.10
iOS 16.4.1

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/a613c695-8ddc-43c8-acc6-459513e5d312"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/4e0a0f29-989e-4ca5-8c33-1455eb661643"  width="300" height="auto"/> </th>
  </tr>
</table>
