### ISSUE TITLE
Broken SVG icon mx_man_made

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#4351]
### Description
Drawing a vector `svg` icon is displayed without the bottom part - if we look closely, the bottom part is a different color, maybe that's the reason.

This name comes up: `mx_man_made`

<details><summary>Additional information</summary>
<img width="900" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/c193307f-94f6-467a-99aa-95d0c319a8b3">
<img width="900" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/06a6e254-4350-4121-b794-3bd28ffa5e48">
<img width="900" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/0d45e149-cb41-484e-8c88-cd8838bfb30e">
</details>

### Steps to reproduce
Go to this place `50.44674° N, 30.51214° E`

### Actual result

<details><summary>iOS</summary>
<img width="900" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/63607213-1b6d-46ff-8eaf-3bb7b25cb74f">
</details>

### Expected result

<details><summary>Android</summary>
<img width="900" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/a98cb5c5-0389-4244-accf-9227432cf730">
</details>

### Your Environment
OsmAnd Version: 4.9.5.4963

**Comment by dmpr0** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/ab4d78ee1f466c93b1591c6142321e2769b4dc9b

**Comment by Zirochkabila** [comment]
# Testing q
`4.9.5.4967`

Different still present

<details><summary>Different</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/5bd35c3b-d3be-4896-a779-2042265d6a92"  width="600" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/4188789c-1ba5-4ab0-acbd-4d5352e7d332"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>
