### ISSUE TITLE
OsmAnd does not follow the track

### ISSUE THREAD

**Issue by Biker729** [osmandapp/OsmAnd-iOS#4412]
### Description

OsmAnd+ 4.9.10 does not follow the trace

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/5f44786c-0df9-4087-9799-b8e14a9d460f"  width="300" height="auto"/> </th>
  </tr>
</table>

### Actual result

Does not work in bike mode as well as in motorcycle mode

### Expected result

The trace of a track should always be followed 1:1

### Your Environment (required)

Warning: Logs may contain information you deem sensitive.
Review this carefully before posting your issue!

```
OsmAnd Version:
iOS version:
Device model:
```

**Comment by vshcherb** [comment]
Android released 5.0 so issue is fixed. IOS needs to be checked

**Comment by Biker729** [comment]
When will version 5.0 be available for Android? ?

**Comment by Biker729** [comment]
The problem persists in OsmAnd+ 5.0.4. ?

![Image](https://github.com/user-attachments/assets/e2dcbb1d-d7bb-4d44-8a07-c897d231d016)

**Comment by Biker729** [comment]
**The problem still exists in OsmAnd+  5.0.5. 2025-04-17**


![Image](https://github.com/user-attachments/assets/e859d8ae-2ba3-4fc2-9b07-938561f8dcb7)

![Image](https://github.com/user-attachments/assets/7d78c37c-93ce-4743-8ddc-bdcdb7f8a4ab)

**Comment by DmitryAlexei** [comment]
@Biker729 Your issue hasn't been fixed yet. Hopefully, it will in 5.1 release

**Comment by Vladyslav-lys** [comment]
https://osmand.net/docs/user/navigation/guidance/navigation-settings#detailed-track-guidance

The Detailed track guidance feature improves the accuracy of route navigation when using track-based routes. When you select a track as the destination, you can enable the Attach to the roads setting from the Follow track menu. This ensures the track is aligned with existing roads for smoother, more precise navigation.

There are two options for using Detailed track guidance:

 • Ask every time (default settings) – The Attach to the roads option will appear in the Route Details section each time a track-based route is calculated. This allows you to decide whether to apply road attachment for each navigation session.
 • Always – The road attachment process will be applied automatically for every navigation by track route without requiring manual confirmation.

When the user selects the Always option, a Threshold distance value must be set. By default, it is 50 meters. Depending on this value, the trace will be attached to the track accordingly. The smaller the Threshold distance, the closer the trace will appear to the track.

**Comment by Vladyslav-lys** [comment]
![Image](https://github.com/user-attachments/assets/d6f002ed-c969-465c-863c-90d42e0dfdca)
![Image](https://github.com/user-attachments/assets/6436d411-7f8c-42bf-ba77-e451eb4aa1b1)

**Comment by Vladyslav-lys** [comment]
![Image](https://github.com/user-attachments/assets/40557c64-3c7f-4f25-9157-473d78547846)
![Image](https://github.com/user-attachments/assets/619848c2-f47f-439b-8877-15d651618955)

**Comment by Vladyslav-lys** [comment]
![Image](https://github.com/user-attachments/assets/325a651a-29dc-4de5-9834-603d691c7f8e)
![Image](https://github.com/user-attachments/assets/80f0fb7d-25ca-4780-92b7-ea544740d6b9)

**Comment by Vladyslav-lys** [comment]
![Image](https://github.com/user-attachments/assets/e674da4a-92c6-468a-a3d6-c5dbbd053554) ![Image](https://github.com/user-attachments/assets/ffd70d44-832e-4e88-82da-59949f02bf22)

**Comment by Zirochkabila** [comment]
`5020`
`OsmAnd~ 5.1.0#5130m, Дата випуску: 2025-05-02`

[OSM](https://www.openstreetmap.org/way/445154337)
[OSM](https://www.openstreetmap.org/way/575700843)

@Biker729 I think that track binding works correctly, since the following parts of the road have restrictions (motor_vehicle=no)
As you can see in the screenshots above - when you set a higher threshold (https://osmand.net/docs/user/navigation/setup/gpx-navigation#attach-to-the-roads) value, the route is routed to the nearest road segment where there are no restrictions
