### ISSUE TITLE
[bug] missing French translation in itinerary parameters

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-ios#568]
In osmand 3.21, when I’m planning an itinerary and that I want to avoid certain roads, I got missing French translation :
![FF0C4C69-DDF2-49C0-ADFF-C8587DC8B4BB](https://user-images.githubusercontent.com/59312735/72972160-39775a00-3dcb-11ea-9dea-861f3e62ffe5.jpeg)

**Comment by vshcherb** [comment]
Should be fixed from Android translation 
<string name="routing_attr_avoid_sett_name">Éviter les pavés</string>
    <string name="routing_attr_avoid_sett_description">Éviter les pavés</string>

**Comment by nabilys** [comment]
The bug still occurs for now (osmand 3.26) 
![5EF1A232-C0F1-4F94-B1F2-1C6573EB6CDD](https://user-images.githubusercontent.com/59312735/74332359-d6f3f700-4d95-11ea-9788-89feb993920f.jpeg)

**Comment by nabilys** [comment]
@vshcherb also, in « analyse » which is a new section I have those missing translations in osmand 3.28 :
![9796FBBC-21F1-4DB3-A2C6-3DFFDBFA0596](https://user-images.githubusercontent.com/59312735/75026659-a3a01f00-549d-11ea-84ea-735d0c13b66d.jpeg)
![FFEB3C2C-93FA-4C8E-9A95-3B77AA8F96BE](https://user-images.githubusercontent.com/59312735/75026664-a4d14c00-549d-11ea-8b11-2fe4498a2340.jpeg)
