### ISSUE TITLE
maxspeed limit interpretation wrong

### ISSUE THREAD

**Issue by WizoneDE** [osmandapp/OsmAnd-iOS#674]
Problem: 
When driving with OSMAND only speed limits (top right box) and speedlimit warning (the big icon and sound ) are only showing up when maxspeed is set as Maxspeed:Forward or maxspeed:backward .

If maxspeed=* is set the speed limit recognition of osmand only works in "lane backwards" direction. If you are driving in the same direction as the orientation of the lane, osmand will ignore the maxspeed=* attribute an not showing the box top right, and not warning for speedlimits.

**Comment by WizoneDE** [comment]
Still the Sam with iOS app 3.13 based on direction of the lane it will show the speed limit info while driving with or without destination set 

![image](https://user-images.githubusercontent.com/35132439/80993721-da01ff00-8e3b-11ea-80cb-e2f8753c187f.png)

![image](https://user-images.githubusercontent.com/35132439/80993741-e2f2d080-8e3b-11ea-9b00-59be8de4a4e1.png)

![image](https://user-images.githubusercontent.com/35132439/80993760-ebe3a200-8e3b-11ea-9b63-9ff38cd73698.png)


![image](https://user-images.githubusercontent.com/35132439/80993775-f43bdd00-8e3b-11ea-96db-dd2b82181c1e.png)

![image](https://user-images.githubusercontent.com/35132439/80993793-faca5480-8e3b-11ea-8685-1ffd069e0b49.png)

**Comment by max-klaus** [comment]
Do you use may be OsmAnd Live? If yes - please try to update regular local map (Germany - Rhineland-Palatinate).

**Comment by WizoneDE** [comment]
yes and it is set to every hour and was updated to the lasted osm version before driving.

**Comment by max-klaus** [comment]
So "Germany - Rhineland-Palatinate" map created on 1 Apr 2020, right?

**Comment by WizoneDE** [comment]
Currently installed:
Germany - Rhineland-Palatinate
- MAP Creation: 1 Apr 2020, 2 AM
- Live Sync: 5 Apr 2020, 1:27 PM

Germany - Hesse
- MAP Creation: 1 Apr 2020, 2AM
- Live Sync: 5 Apr 2020, 1:27 PM

live Sync yesterday evening was showing 4 Apr 2020, 6:31 PM before starting driving

**Comment by WizoneDE** [comment]
not fixed in 3.14 release

**Comment by max-klaus** [comment]
> not fixed in 3.14 release

Could you please specify what issues from the list are not fixed?

**Comment by max-klaus** [comment]
Should be fixed by https://github.com/osmandapp/OsmAnd-iOS/commit/19b0f346e1f00878166b6b5e6434f370655fc96d

**Comment by WizoneDE** [comment]
@max-klaus 
There is only one issue in this topic, don‘t get your question. :(

Tested maxspeed again and it is still not working on 3.14 so currently not fixed.

In which release will 19b0f34 be included to check again?

**Comment by max-klaus** [comment]
Actually there are two issues:
1 - when you are following a calculated route
2 - driving without calculated route

Release (3.14) should contain fix for the first case. Next release will contain fix for the second case and also small fix for lanes widget (lack straight arrows in some cases).

**Comment by WizoneDE** [comment]
When using demo mode for a calculated route and the maxspeed are not showing up in 3.14 is this because demo route is 2. ?

If not, 1. is still broken in 3.14 release

**Comment by max-klaus** [comment]
I think it should be fixed in the next release. Currently you may test it in the beta version (3.15) - https://testflight.apple.com/join/7poGNCKy
